.TH calculations 1 "June 10, 2022" "user manual"
.SH NAME
.PP
calculations.py - accepts user input and completes various calculations
.SH SYNOPSIS
.PP
 usage - './calculations.py'
 
.SH DESCRIPTION
.PP

This program accepts input from the user and runs the input 
through various functions.

.SH FUNCTION DESCRIPTIONS
.PP

1. def main():
PURPOSE - accepts user input of either an integer, float, or word, then casts the input to various designated functions.

a. try/except/else - determines what input the user submitted and routes to specified program section.


2. def calculations(val):

PURPOSE - if user provides an integer or float, function will complete various calculations.


3. def more_calculations(val):

PURPOSE - if user provides an integer or float, function will complete calculations within.


4. def siblings(): 

PURPOSE - 


5. def utilities():

PURPOSE -

6. def subway():

PURPOSE -

7. def demo_text(val):

PURPOSE -


.SH LICENSE
.PP	  
	


.PP
.SH AUTHOR
CW2 Kyle Spicer
